#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"
  block compile yarn

  mkdir -p "$shome/vendor"
  git clone https://github.com/pantsel/konga.git "$shome/vendor/konga-${KONGA_VERSION}" || true
  cd "$shome/vendor/konga-${KONGA_VERSION}"
  git fetch
  git reset --hard "${KONGA_VERSION}"
  block compile yarn

  rm -rf "$shome/vendor/konga"
  ln -nfs "konga-${KONGA_VERSION}" "$shome/vendor/konga"
}

main "$@"
