#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_konga="$(cat "$shome/vendor/konga/package.json" 2>/dev/null | jq -r '.version' || true)"
  jq -n --arg konga "$ver_konga" '{konga: $konga}'
}

version "$@"
