#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_konga="0.0.1"
  jq -n --arg konga "$ver_konga" '{konga: $konga}'
}

version "$@"
